### ISSUE TITLE
why is that the generated poetry doesn't contain the keywords？

### ISSUE THREAD

**Issue by mengmengwang90** [DevinZ1993/Chinese-Poetry-Generator#5]
why is that the generated poem doesn't contain the keywords？
Input Text:	春天桃花开了
Keywords:	桃花开 相宜 春天 江边
Poem Generated:       
        梅花香满绿荫时，石木无春午六滨。
	江水东归灯下望，江南车径与谁槟。
In the paper “ChinesePoetryGenerationwithPlanningbasedNeuralNetwork”，it seems that the generated poem contains the keywords.
![1505962616 1](https://user-images.githubusercontent.com/3798692/30676982-a361de7e-9ebb-11e7-8748-6be1b15fe074.jpg)

**Comment by DevinZ1993** [comment]
Sorry for the delay. I didn't follow the original paper completely. That maybe the cause of this problem.
Thx.
