### ISSUE TITLE
what's the source of qtais.txt?

### ISSUE THREAD

**Issue by shizhediao** [DevinZ1993/Chinese-Poetry-Generator#6]
I know the meaning of corpus following:
qts : 全唐诗
qsc : 全宋诗
qsc : 全宋词
yuan ：元朝诗歌
ming：明代诗歌
qing: 清代诗歌
Am I correct?
And what's the meaning of qtais.txt?

thanks!

**Comment by DevinZ1993** [comment]
Hi there,

I used the same corpus as Zhang and Lapata (EMNLP, 2014), which can be downloaded from [here](http://homepages.inf.ed.ac.uk/mlap/Data/EMNLP14/). But I don't know what qtais.txt is either.

**Comment by shizhediao** [comment]
OK, thanks!
