### ISSUE TITLE
Thank you for your contribution and have two requests

### ISSUE THREAD

**Issue by AlphaWill0** [DevinZ1993/Chinese-Poetry-Generator#8]
hi，author：
this is good job，thank you for your share !  I have two request：
can you explain the process of keyword extraction , key word expansion and generation based on keyword?
In addition，do you have the code of   Zhe Wang et al. Chinese Poetry Generation with Planning based Neural Network. 2016 ?  
looking forward to your reply，thanks！

**Comment by DevinZ1993** [comment]
Hi there,

Keyword extraction is based on the TextRank algorithm, wherein each word except stopwords is granted a rank when considered as a keyword candidate.

Keyword expansion is based on the word2vec model of the gensim library. Similar words are generated as per the input text (extracted keywords).

Poem generation is based on a simple RNN encoder-decoder framework. To generate a sentence, a keyword should be fed as the decoder input, and the encoder generates the sentence char by char. The state vector is passed from one sentence to another to sort of maintain the "context".

As to the original paper, I'm not sure the authors have made public their own code.

Wish this could help.

**Comment by AlphaWill0** [comment]
Thank you for your reply!
This is a great help to me and I would like to ask a little more. the process of  the word2vec model train word vector, train dataset is come from the poem, is it ?

**Comment by DevinZ1993** [comment]
Yup. I only used the poem corpus as training sets, cuz I assume ancient poems and modern Chinese corpus are slightly different.

**Comment by AlphaWill0** [comment]
hi，
![image](https://user-images.githubusercontent.com/13504420/34197686-8550b026-e5a2-11e7-8cbd-526d4fe43815.png)
I feel the effect of  word expanding  is not good, maybe is the reason of training sets.
Can give me a contact information, such as email WeChat or QQ,. I want to discuss with you more poems generated by the details.

**Comment by AlphaWill0** [comment]
My email is 824396385@qq.com. Look forward to your letter.

**Comment by DevinZ1993** [comment]
Hi there,

Thank you for your interests in this project. You are right. The word expansion is definitely far from good. The original paper has proposed a better solution based on the RNN language model.

Yet it is not my intention to update this project right now. If time permits, I would like to refactor the entire project in future to accommodate to better algorithms, but not at this point.

Anyway, any remarks or suggestions are welcome.

**Comment by hacker-mao** [comment]
![image](https://user-images.githubusercontent.com/34244245/41577854-d2294e0a-73c1-11e8-8339-8f7f72eb846f.png)
Why i can't run this py successful.I have prepare for 
Python 2.7
TensorFlow 1.0
Jieba 0.38
Gensim 2.0.0

**Comment by DevinZ1993** [comment]
Current code has migrated to python3 and tf 1.8. I'm not sure what was wrong back in Jun 2018.

**Comment by hacker-mao** [comment]
ok  thank you




------------------ 原始邮件 ------------------
发件人: "Devin Zuo"<notifications@github.com>;
发送时间: 2018年8月31日(星期五) 中午12:57
收件人: "DevinZ1993/Chinese-Poetry-Generation"<Chinese-Poetry-Generation@noreply.github.com>;
抄送: "hacker_mao"<hacker_mao@foxmail.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [DevinZ1993/Chinese-Poetry-Generation] Thank you for yourcontribution and have two requests (#8)




Current code has migrated to python3 and tf 1.8. I'm not sure what was wrong back in Jun 2018.
