### ISSUE TITLE
what's the difference between two word2vec model?

### ISSUE THREAD

**Issue by shizhediao** [DevinZ1993/Chinese-Poetry-Generator#9]
I find there are two word2vec model
one is in plan.py, we train a model called kw_model.bin
another one is in word2vec.py, we train a model called word2vec.npy
I think both of their input is quatrains
so what's the difference between them?
THX

**Comment by DevinZ1993** [comment]
Plan.py uses word2vec for word planning. To be more specific, we generate similar words to the given user input when the extracted keywords are not sufficient.

word2vec.py uses word2vec to do word embedding, which basically means mapping Chinese character set into a high dimensional vector space.

The both cases use the gensim library.

**Comment by DevinZ1993** [comment]
Closed for now. For further questions, please reopen it.
